### ISSUE TITLE
Unable to type in command line

### ISSUE THREAD

**Issue by randomuserhi** [apsun/AbsoluteTouch#7]
Hi there, this is a really neat program that u've made 😄 

However, I can't seem to type in the command line (for the commands like -c etc), when I do try nothing happens (cntrl-c does work though the lose the program). Apart from that everything else seems to work as intended.

I'm using windows 10 and I have a dell touchpad (though it still uses synaptic drivers)

**Comment by apsun** [comment]
You seem to be running the program directly, instead of through a console. That's expected - you need to give the parameters when you start the program, not while the program is running. Instead of running AbsoluteTouch.exe directly, run Command Prompt or PowerShell first and type in AbsoluteTouch.exe followed by any arguments that you want. For example, for `-c`, you would run cmd/ps and then enter the following:

`C:\Where\Ever\You\Saved\AbsoluteTouch.exe -c`

**Comment by randomuserhi** [comment]
Ah, thank you it works now. Much appreciated :D
